export const wardNames = [
  { key: '1', value: 'Bopal' },
  { key: '2', value: 'Bapunagar' },
  { key: '3', value: 'Ghatlodiya' },
  { key: '4', value: 'Krishnanagar' },
  { key: '5', value: 'Maninagar' },
  { key: '6', value: 'Naroda' },
  { key: '7', value: 'Nirnaynagar' },
  { key: '8', value: 'Nirnaynagar' },
  { key: '9', value: 'Noblenagar' },
  { key: '10', value: 'Odhav' },
  { key: '11', value: 'Sabarmati' },
  { key: '12', value: 'Sabarmati' },
  { key: '13', value: 'Thaltej' },
  { key: '14', value: 'Vastrapur' },
  { key: '15', value: 'Vejalpur' },
];
